### ISSUE TITLE
Why abandon the TiledBackingStore technology

### ISSUE THREAD

**Issue by flagflag** [ychin/EAWebKit#7]

**Comment by ychin** [comment]
Sorry, what's the question here?

**Comment by ychin** [comment]
Also, this is just a mirror of the official EA location (https://gpl.ea.com/eawebkit.html) just to make it easier for people to try and use EA WebKit because the official location isn't version controlled. I haven't really worked on EAWebKit much in a long time and it doesn't seem like EA has shipped a new version in a while either.

**Comment by flagflag** [comment]
Thank you so much
